import { Icon } from "@iconify/react";
import { useContext } from "react";
import Head from "next/head";
import Message from "../components/Message";
import { messages } from "../data/messages";
import { AppContext } from "../components/Layout";

export default function ChannelPage() {
  const { setDrawer } = useContext(AppContext);

  const openDrawer = () => {
    setDrawer(true);
  };

  return (
    <>
      <Head>
        <title>Chat App | Frontend Devs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="relative px-4 pt-16 pb-20 mx-auto bg-zinc-800 min-h-screen">
        {/* top bar */}
        <div className="fixed text-gray-50 top-0 left-0 w-full bg-zinc-800 drop-shadow-lg p-4 flex">
          <button onClick={openDrawer} className="text-2xl">
            <Icon icon="charm:menu-hamburger" />
          </button>

          <h1 className="text-md font-semibold mt-0.5 pl-4">
            FRONT-END DEVELOPERS
          </h1>
        </div>

        {messages.data?.map((item, index) => (
          <div key={index}>
            <Message name={item.name} date={item.date} message={item.message} />
          </div>
        ))}

        {/* input bar */}
        <div className="fixed bottom-0 left-0 w-full py-4 px-5 bg-zinc-800">
          <div className="w-full py-2 pl-5 pr-2 rounded-lg bg-zinc-600/50 flex justify-between">
            <input
              className="bg-transparent outline-none border-none text-white"
              type="text"
              placeholder="Type a message here"
              name="message"
              id="message-input"
            />
            <button className="text-white text-xl bg-blue-500 w-9 h-9 rounded-lg grid place-content-center">
              <Icon icon="fe:paper-plane" />
            </button>
          </div>
        </div>
      </div>
    </>
  );
}
