import Head from "next/head";
import Image from "next/image";
import Message from "../components/Message";
import { messages } from "../data/messages";

export default function ChannelPage() {
  return (
    <>
      <Head>
        <title>Chat App | Frontend Devs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative container px-4 pb-4 mx-auto bg-gray-800 min-h-screen">
        {messages.data?.map((item, index) => (
          <div
            key={index}
            className={`${index === messages.data.length - 1 && "pb-16"} `}
          >
            <Message name={item.name} date={item.date} message={item.message} />
          </div>
        ))}

        {/* input bar */}
        <div className="fixed bottom-0 left-0 w-full py-4 px-5 bg-gray-800">
          <div className="w-full py-4 px-5 rounded-lg bg-zinc-600/50 ">
            <input
              className="bg-transparent outline-none border-none text-white"
              type="text"
              placeholder="Type a message here"
              name="message"
              id="message-input"
            />
          </div>
        </div>
      </main>
    </>
  );
}
